<?php

include_once "_mod.php";

#
#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#
#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#
#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

$max = 3000;
$list = getPentagonalList($max);
$list_flipped = array_flip($list);
$result = PHP_INT_MAX;

for($i = 0; $i < $max; $i++) {
    for($j = $i + 1; $j < $max; $j++) {
        $sum = $list[$j] + $list[$i];
        $diff = $list[$j] - $list[$i];
        if(array_key_exists($sum, $list_flipped)) {
            if (array_key_exists($diff, $list_flipped)) {
                e('diff exists');
                if ($diff < $result) {
                    $result = $diff;
                }
            }
        }
    }
}
e($result);

function getPentagonalList($num) {
    $result = [];
    $i = 1;
    while(count($result) < $num) {
        $temp = $i * ($i * 3 - 1)/2;
        if(is_int($temp)) {
            $result[] = $temp;
        }
        $i++;
    }
    return $result;
}
