<?php

include_once "_mod.php";

#
#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
#Triangle       Tn=n(n+1)/2     1, 3, 6,  10, 15, ...
#Pentagonal     Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
#Hexagonal      Hn=n(2n−1)      1, 6, 15, 28, 45, ...
#It can be verified that T285 = P165 = H143 = 40755.
#
#Find the next triangle number that is also pentagonal and hexagonal.

#n^2 + n - 2T = 0; 
#3*n^2 - n - 2P = 0;
#
#n = -b + sqrt(b^2 - 4ac) / 2a
#
#n = -1 + sqrt(1 + 8T) / 2
#n = 1 + sqrt(1 + 24P) / 6

#nが自然数になる場合を求める


$i = 144;
while(true) {
    $val = $i*(2*$i - 1);
    if(isPentagonal($val) && isTriangle($val)) {
        e($val);
        break;
    }
    $i++;
}

function isTriangle($num) {
    $n = (-1 + sqrt(1+8*$num)) / 2;
    return $n > 0 && floor($n) == ceil($n);
}

function isPentagonal($num) {
    $n = (1 + sqrt(1+24*$num)) / 6;
    return $n > 0 && floor($n) == ceil($n);
}
